### ISSUE TITLE
debugging warnings and errors when viewing a course's files when no files exist in the course

### ISSUE THREAD

**Issue by danmarsden** [k-rokicki/moodle-local_coursefiles#1]
Warning: asort() expects parameter 1 to be array, null given in /home/dan/www/moodle/local/coursefiles/classes/course_files.php on line 234
Exception - Unsupported operand types

[More information about this error](https://docs.moodle.org/401/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 239 of /local/coursefiles/classes/course_files.php: Error thrown
line 62 of /local/coursefiles/classes/output/renderer.php: call to local_coursefiles\course_files->get_components()
line 82 of /local/coursefiles/index.php: call to local_coursefiles\output\renderer->overview_page()

**Comment by k-rokicki** [comment]
Can't believe I didn't test that case - thanks for catching it, fixed in 4d5849b70a37da99c21bbbc334842d2255e7411f
