### ISSUE TITLE
plugin should implement it's own capability 

### ISSUE THREAD

**Issue by danmarsden** [k-rokicki/moodle-local_coursefiles#3]
You need to implement a new capability in your plugin (you can give it to students and teachers by default) - but you need to then check that users have this capability before allowing them to view the report (and before adding the link to the navigation)

**Comment by k-rokicki** [comment]
Thank you - I've added the `local/coursefiles:view` and `local/coursefiles:download` capabilities in dcc81ee0c5824a8c6c95a3baa270dae0568c5d0a
